spring:
  datasource:
    url: jdbc:mysql://mysql:3306/capstone?useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: "root"
    password: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver